platform :ios, '8.0'
target 'QYZJAPP' do
pod "MJRefresh"
pod 'AFNetworking'
pod 'SDWebImage'
pod "SVProgressHUD"
pod 'MJExtension'
pod 'IQKeyboardManager'
pod 'SwipeBack'

pod 'UMengUShare/UI'
pod 'UMengUShare/Social/Sina'
pod 'UMengUShare/Social/WeChat'
pod 'UMengUShare/Social/QQ'

pod 'ReactiveObjC'
pod 'TZImagePickerController'
pod 'Masonry'
pod 'ZFPlayer'


end
